language: node_js
# nodejs版本
node_js:
  - '8'

# Travis-CI Caching
cache:
  yarn: true
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - yarn install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - yarn ci
  - yarn build

after_script:

deploy:
  provider: script
  script: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN} && npm publish
  on:
    all_branches: true




#deploy:
#  provider: script
#  script: deploy.sh
#  on:
#    all_branches: true
#    tags: true


#指定分支，只有指定的分支提交时才会运行脚本
#branches:
#  only:
#    - master