language: node_js
# nodejs版本
node_js:
  - '8'

# Travis-CI Caching
cache:
  yarn: true
  directories:
    - node_modules

# S: Build Lifecycle




jobs:
  include:
  - stage: "init"
    name: "yarn install"
    install:
      - yarn install

  - stage: "test"
    name: "yarn ci"
    script:
      - yarn ci

  - stage: "build"
    name: "yarn build"
    script: yarn build


  - stage: "deploy"
    name: "npm publish"
    deploy:
      provider: script
      skip_cleanup: true
      script: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        - script: npm publish
      on:
        all_branches: true

stages:
  - init
  - build
  - test
  - deploy
#  - name: deploy
#    if: branch = xingxiaodong


#指定分支，只有指定的分支提交时才会运行脚本
#branches:
#  only:
#    - master