language: node_js
# nodejs版本
node_js:
  - '8'

# Travis-CI Caching
cache:
  yarn: true
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - yarn install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - yarn ci
  - yarn build

after_script:

  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm publish
#  - cd ./dist
#  - git init
#  - git config user.name "${U_NAME}"
#  - git config user.email "${U_EMAIL}"
#  - git add .
#  - git commit -m "Update tools"
#  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
#branches:
#  only:
#    - master